name: Feature Testing the Database server
on:
  push:
    branches:
      - feature/*
jobs: 
  execute_feature:
    environment: nonprod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Perform a SQL Database copy for feature testing
        run: |
          ./scripts/clone-db.sh -f create -g ${{ vars.RESOURCE_GROUP }} -n ${{ vars.SERVER }} -b ${{ vars.DB_NAME }} -e ${{ vars.SERVER }} -i "${{ github.ref }}" -d false
        # run: |
        #   echo "Copying database for feature testing...!!!"
        #   FULL_NAME="${{ github.ref }}"
        #   CLEAN_NAME=$(echo "$FULL_NAME" | sed 's|refs/heads/||' | tr '/' '-')
        #   CLEAN_NAME=$(echo "$CLEAN_NAME" | tr '/_' '-')
        #   SUFFIX=$(echo "$CLEAN_NAME" | cut -c1-10)
        #   echo "SUFFIX=$SUFFIX" >> $GITHUB_ENV
        #   az sql db copy --dest-name ${{ vars.DB_NAME }}-${SUFFIX} \
        #     --name ${{ vars.DB_NAME }} \
        #     --resource-group ${{ vars.RESOURCE_GROUP }} \
        #     --server ${{ vars.SERVER }} \
        #     --dest-resource-group ${{ vars.RESOURCE_GROUP }} \
        #     --dest-server ${{ vars.SERVER }}
      - name: Database copy Success
        run: echo "Database copy for feature testing completed successfully."

      - name: Execute SQL Scripts
        uses: azure/sql-action@v2.3
        with:        
            connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
            path: './stored_procedures/*.sql'
            skip-firewall-check: true
        
      - name: Notify failure
        if: failure()
        run: echo "Some feature tests failed. Please check the logs."
    