name: Feature Testing the Database server
on:
  push:
    branches:
      - feature/*
jobs: 
  execute_feature:
    environment: nonprod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Perform a SQL Database copy for feature testing
        run: |
          ./scripts/clone-db.sh -f create -g ${{ vars.RESOURCE_GROUP }} -n ${{ vars.SERVER }} -b ${{ vars.DB_NAME }} -e ${{ vars.SERVER }} -i "${{ github.ref }}" -d false

      - name: Database copy Success
        run: echo "Database copy for feature testing completed successfully."

      - name: Setup Connection String
        run: |
            UPDATED_CONN_STR=$(echo "${{ secrets.AZURE_SQL_CONNECTION_STRING }}" | sed -E "s/(Initial Catalog=)[^;]+/\1${FULL_DB_NAME}/")
            echo "UPDATED_CONN_STR=$UPDATED_CONN_STR" >> $GITHUB_ENV

      - name: Prepare SQL Scripts for exection
        run: |
            for f in stored_procedures/*.sql; do
                cat "$f"
                echo -e "\n-- End of $f\n"
            done > stored_procedures/combined.sql

      - name: Execute SQL Scripts
        uses: azure/sql-action@v2.3
        with:        
            # connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
            connection-string: ${{ env.UPDATED_CONN_STR }}
            path: './stored_procedures/combined.sql'
            skip-firewall-check: true
        
      - name: Notify failure
        if: failure()
        run: echo "Some feature tests failed. Please check the logs."
    